# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([5, 8, 3, 1, 11])
print(array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sorted_array = np.sort(array)
print(sorted_array)

[ 5  8  3  1 11]
[ 1  3  5  8 11]


# Problem 2

In [20]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array = np.array([10, 15, 30, 45, 60])
print(array)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arr = np.arange(5, 16)
print(arr)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arr = np.arange(50, 101, 5)
print(arr)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arr_zeros = np.zeros(10)
print(arr_zeros)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arr_ones = np.ones(10)
print(arr_ones)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arr = np.linspace(0, 100, 5)
print(arr)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arr = np.random.randint(10, 31, size=5)
print(arr)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arr = np.random.uniform(-1, 2, size=10)
print(arr)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10, 51, size=(3, 5))
print(arr)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_total = np.sum(matrix, axis=1)
column_total = np.sum(matrix, axis=0)

print("Row total:", row_total)
print("Column total: ", column_total)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
min_value = np.max(matrix)
max_value = np.min(matrix)
mean_matrix = np.mean(matrix)

print("Max value:", max_value)
print("Min value:", min_value)
print("Matrix mean:", mean_matrix)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.argmax(matrix)
print(max_index)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arr = np.arange(10, 21)
sample_arr = arr[:3]

print(sample_arr)
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
arr_1 = arr[::-1]

print(arr_1)
# 15- Üretilen matrisin ilk satırını seçiniz.
print(matrix[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matrix[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matrix[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.square(matrix))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrix = np.random.randint(-50, 51, size=(3, 5))
print(matrix[(matrix > 0) & (matrix % 2 == 0)])

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[13 10 25 21 18]
[ 1.84390447 -0.80689026 -0.53727434  0.8540002   0.50788746  1.08540855
 -0.75089642 -0.62923419  0.63902869 -0.59086618]
[ 1.84390447 -0.80689026 -0.53727434  0.8540002   0.50788746  1.08540855
 -0.75089642 -0.62923419  0.63902869 -0.59086618]
Row total: [168 156 165]
Column total:  [121  74 127  45 122]
Max value: 11
Min value: 47
Matrix mean: 32.6
7
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[46 29 35 16 42]
47
[46 42 33]
[[2116  841 1225  256 1764]
 [1764  144 2209  324 1369]
 [1089 1089 2025  121 1849]]
[ 2 38]
