# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix = np.random.randint(0, 11, size=5)
print(matrix)
# 3 - matris'in boyutunu öğrenin
print(matrix.shape)
# 4 - matris'i yeniden boyutlandırın
new_matrix =matrix.reshape(1, 5)
print(new_matrix)
# 5 - matris'in boyut sayısını öğrenin
print(matrix.ndim)

[ 5  1  1 10  4]
(5,)
[[ 5  1  1 10  4]]
1


# Problem 2

In [21]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matrix_1 = np.arange(1, 11, 2)
print(matrix_1)
# 2 - Oluşturduğunuz matrisi parçalayın
matrix_2 = matrix_1[:3]
print(matrix_2)
# 3 - Parçalanmış matrisleri birleştirin
final_matrix = np.concatenate((matrix_2, matrix_1))
print(final_matrix)

[1 3 5 7 9]
[1 3 5]
[1 3 5 1 3 5 7 9]


# Problem 3

In [22]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matrix = np.random.choice(np.arange(5, 101, 2), size=(2, 5))
print(matrix)
# 2 - matris'in özelliklerini inceleyin
print("Dimension: ", matrix.ndim)
print("Shape: ", matrix.shape)
print("Size: ", matrix.size)


[[71 41 55 65 59]
 [31 79 57 35 79]]
Dimension:  2
Shape:  (2, 5)
Size:  10
